const AGORA_APP_ID = process.env.NEXT_PUBLIC_AGORA_APP_ID ?? '';
const AGORA_CUSTOMER_KEY = process.env.NEXT_PUBLIC_AGORA_CUSTOMER_KEY ?? '';
const AGORA_CUSTOMER_SECRET =
  process.env.NEXT_PUBLIC_AGORA_CUSTOMER_SECRET ?? '';
const AGORA_CHANNEL = process.env.NEXT_PUBLIC_TEMP_AGORA_CHANNEL ?? '';
const AGORA_TOKEN = process.env.NEXT_PUBLIC_TEMP_AGORA_TOKEN ?? '';

export {
  AGORA_APP_ID,
  AGORA_CUSTOMER_KEY,
  AGORA_CUSTOMER_SECRET,
  AGORA_CHANNEL,
  AGORA_TOKEN,
};
